_BASE_: "../Base-RCNN-FPN-KINS.yaml"
MODEL:
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: "Parallel_Amodal_Visible_ROIHeads"
  ROI_MASK_HEAD:
    NAME: "Parallel_Amodal_Visible_Head"
TEST:
  EVAL_AMODAL_TYPE: "AMODAL_VISIBLE"
OUTPUT:
  TRAIN_VERSION: 'mask_rcnn_parallel_kins_res50_SGD_1x'